title: sntrpc
default_lang: en
author:
  name: sntrpc
  email: son@sntrpc.com
taxonomies:
  - category
  - tag
metadata:
  description: 'sntrpc, Son Vo'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
