enabled: true
header:
  name: sntrpc
  subtitle: 'avant garde'
  social:
    facebook: 'https://facebook.com/sntrpc'
    twitter: 'https://twitter.com/sntrpc'
    linkedin: 'https://linkedin.com/in/sntrpc'
  image: {  }
